#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define INIT_FAILED 8932
#define INIT_SUCCESS 8933
#define GLFW_INIT_FAILED 8734
#define GLFW_WINDOW_CREATE_FAILED 5404
#define GLAD_INIT_FAILED 1872

#endif